kind: pipeline
type: docker
name: default

workspace:
  path: /src

steps:
  - name: prepare-node-modules
    volumes:
      - name: node
        path: /src/frontend/node_modules
    image: node:13
    commands:
      - cd frontend
      - yarn --frozen-lockfile
  - name: frontend-formatting
    volumes:
      - name: node
        path: /src/frontend/node_modules
    image: node:13
    commands:
      - cd frontend
      - yarn fmt -c
    depends_on:
      - prepare-node-modules
  - name: frontend-tests
    volumes:
      - name: node
        path: /src/frontend/node_modules
    image: node:13
    commands:
      - cd frontend
      - yarn test
    depends_on:
      - prepare-node-modules
  - name: frontend-build
    volumes:
      - name: node
        path: /src/frontend/node_modules
      - name: templates
        path: /src/templates
    image: node:13
    commands:
      - cd frontend
      - yarn build
    depends_on:
      - frontend-tests
  - name: backend-install
    volumes:
      - name: go
        path: /go
    image: golang:1.13
    commands:
      - go mod download
      - scripts/install_tools.sh
  - name: backend-formatting
    volumes:
      - name: go
        path: /go
    image: golang:1.13
    commands:
     - test -z "$(goimports -l . | tee /dev/stderr)"
    depends_on:
      - backend-install
  - name: backend-tests
    image: golang:1.13
    volumes:
      - name: go
        path: /go
      - name: templates
        path: /src/templates
    commands:
      - go generate
      - go vet ./...
      - scripts/setup_db.sh # Ensure the database test data is loaded
      - go test ./...
    depends_on:
      - backend-install
      - frontend-build
  - name: build
    image: golang:1.13
    volumes:
      - name: go
        path: /go
      - name: templates
        path: /src/templates
    commands:
      - go generate
      - go build cmd/kjudge/main.go
      - go build -tags production cmd/kjudge/main.go
    depends_on:
      - frontend-tests
      - backend-tests

volumes:
  - name: templates
    temp: {}
  - name: go
    temp: {}
  - name: node
    temp: {}

trigger:
  event:
    - push
